#!/usr/bin/env node

const fs = require('fs')
const path = require('path')

const componentName = process.argv[2]

const vueTpl = `<template src="./template.html"></template>
<script src="./script.js"></script>
<style src="./style.css"></style>
`

const templateTpl = `<div class="${componentName}-wrap">
  <p>${componentName} component</p>
</div>
`

const scriptTpl = `export default {
  created () {},
  data () {
    return {}
  },
  methods: {}
}
`

const styleTpl = `.${componentName}-wrap {
  /* style here */
}
`

const componentAbsPath = path.join(__dirname, `../src/components/${componentName}`)

fs.mkdir(componentAbsPath, err => {
  if (err) {
    console.error(`组件创建失败！`)
    console.error('    ' + err.message)
    return
  }
  fs.writeFile(path.join(componentAbsPath, '/index.vue'), vueTpl,() => {})
  fs.writeFile(path.join(componentAbsPath, '/template.html'), templateTpl, () => {})
  fs.writeFile(path.join(componentAbsPath, '/script.js'), scriptTpl, () => {})
  fs.writeFile(path.join(componentAbsPath, '/style.css'), styleTpl, () => {})
  console.log('组件创建成功！')
})
